name: Check compatibility
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    name: Check source code compatibility
    runs-on: ubuntu-latest
    container: swift:6.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v2
      - name: Run Test
        run: |
          set -eux
          cd Examples/Basic
          swift build --swift-sdk wasm32-unknown-wasi --static-swift-stdlib
          swift build --swift-sdk wasm32-unknown-wasi -Xswiftc -DJAVASCRIPTKIT_WITHOUT_WEAKREFS --static-swift-stdlib
