name: Performance

on: [pull_request]

jobs:
  perf:
    runs-on: ubuntu-latest
    container: swift:6.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v2
      - name: Install dependencies
        run: |
          apt-get update && apt-get install make nodejs npm -y
      - name: Run Benchmark
        run: |
          make bootstrap
          make perf-tester
          node ci/perf-tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
