name: Performance

on: [pull_request]

jobs:
  perf:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/install-swift
        with:
          download-url: https://download.swift.org/swift-6.0.3-release/ubuntu2404/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE-ubuntu24.04.tar.gz
      - uses: swiftwasm/setup-swiftwasm@v2
      - name: Run Benchmark
        run: |
          make bootstrap
          make perf-tester
          node ci/perf-tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
